export default {
    'setup-of-hardware': 'Setup of hardware',
    'supported-hardware': 'Supported hardware',
    'initialize': 'Initialize',
    'frontend-setup': 'Frontend setup',
    'ad-only': 'AD only',
    'da-only': 'DA only',
    'ad-da': 'AD-DA',
    'play': 'Play',
    'rec': 'Rec',
    'mic-calibration': 'Mic. calibration',
    'harmonic-distortion': 'Harmonic distortion',
    'harmonic-distortion-f': 'Harmonic distortion (f)',
    'max-spl': 'Max SPL',
    'multisine-distortion': 'Multisine distortion',
    'frequency-response': 'Frequency response',
    'impedance': 'Impedance',
    'ls-sensitivity': 'LS sensitivity',
    'polar-response': 'Polar response',
    'turn-table-setup': {display: 'hidden'},
    'processing': {display: 'hidden'},
}