export default {
  'channel-work': 'Channel work',
  'read-file': 'Read file',
  'read-file-channels': 'Read file channels',
  'read-file-and-insert-at-active-cursor': 'Read file and insert at active cursor',
  'set-readfilepath-to-filepath': 'Set readfilepath to filepath',
  'write': 'Write',
  'multiply': 'Multiply',
  'add': 'Add',
  'negate': 'Negate',
  'overwrite': 'Overwrite',
  'phase': 'Phase',
  'invert': 'Invert',
  'raise-to-power': 'Raise to power',
  'add-group-delay': 'Add group delay',
  'smooth': 'Smooth',
  'apply-window': 'Apply window',
  'spl-over-time': 'SPL over time',
  'convert-samplerate': 'Convert samplerate',
  'extract': 'Extract',
  'extend': 'Extend',
  'delete-region': 'Delete region',
  'cyclic-move': 'Cyclic move',
  'time-invert': 'Time invert',
  'frac-oct-filtering': 'Frac. oct. filtering',
  'log-average-adjust': 'Log average adjust',
  'differentiate': 'Differentiate',
  'integrate': 'Integrate',
  'remove-dc': 'Remove DC',
  'complex-conjugate': 'Complex conjugate',
  'normalize-spectrum': 'Normalize spectrum',
  'complex-interpolation': 'Complex interpolation',
  'generate': 'Generate',
  'sweep-generator': 'Sweep generator',
  'multisine-generator': 'Multisine generator',
  'create-curve': 'Create curve',
  'set-external-preamp-gain-to-current-signals': 'Set external preamp gain to current signals',
  'set-sensor-sensitivities-to-current-signals': 'Set sensor sensitivities to current signals',
  'a-filtering-iir': 'A-filtering (IIR)',
  'a-unfiltering-iir': 'A-unfiltering (IIR)',
  'a-weighting': 'A-weighting',
  'a-unweighting': 'A-unweighting',
  'filter': 'Filter',
  'distortion-processing': 'Distortion processing',
  'weighting-functions': 'Weighting functions',
  'integrated-impulse-response-processing': 'Integrated impulse response processing',
  'fade-in-out': 'Fade-in-out',
  'sort-signal': 'Sort signal',
  'clip-signal': 'Clip signal',
  'edit-extended-comment': 'Edit extended comment',
  'edit-temp-humi': 'Edit temp humi',
  'region-control': {display: 'hidden'},
  'channel-subset-syntax': {display: 'hidden'},
  'select-channel': {display: 'hidden'},
  'factor-control': {display: 'hidden'},
  'signal-length': {display: 'hidden'},
  'multisine-infos': {display: 'hidden'},
}
