export default {
  'write-string-to-excel-cell': 'Write string to excel cell',
  'user-input': 'User input',
  'user-input-in-next-menu': 'User input in next menu',
  'setup-relais-card-1977xx': 'Setup relais card 1977xx',
  'init-relais-card-1977xx': 'Init. relais card 1977xx',
  'relais-card-1977xx': 'Relais card 1977xx',
  'setup-com-port-communication': 'Setup com port communication',
  'serial-port-communication': 'Serial port communication',
  'wait-seconds': 'Wait seconds',
  'check-tolerance': 'Check tolerance',
  'learn-tolerance': 'Learn tolerance',
  'process-control': 'Process control',
  'external-batch': 'External batch',
  'copy-file': 'Copy file',
  'standard-tolerances': 'Standard tolerances',
  'if-then-else': 'If then else',
  'sht3x': 'SHT3X',
  'meilhaus-1208ls-ad' : {display: 'hidden'},
  'tti-tf930' : {display: 'hidden'},
  'automation' : {display: 'hidden'},
}