export default {
  file: 'File',
  domain: 'Domain',
  display: 'Display',
  'time-signalsspectrums': 'Time Signals/Spectrums',
  edit: 'Edit',
  info: 'Info',
  transform: 'Transform',
  adda: 'ADDA',
  directivity: 'Directivity',
  macro: 'Macro',
  qc: 'QC',
  plot: 'Plot',
  help: 'Help',
  advices: 'Advices',
  shortcuts: 'Shortcuts',
}
