export default {
    'setup-of-hardware': 'Setup of hardware',
    'supported-hardware': 'Supported hardware',
    'initialize': 'Initialize',
    'frontend-setup': 'Frontend setup',
    'ad-only': 'AD only',
    'da-only': 'DA only',
    'ad-da': 'AD-DA',
    'play': 'Play',
    'rec': 'Rec',
    'mic-calibration': 'Mic. calibration',
    'harmonic-distortion': 'Harmonic distortion',
    'harmonic-distortion-f': 'Harmonic distortion (f)',
    'max-spl': 'Max SPL',
    'multisine-distortion': 'Multisine distortion',
    'frequency-response': 'Frequency response',
    'impedance': 'Impedance',
    'ls-sensitivity': 'LS sensitivity',
    'polar-response': 'Polar response',
    'turn-table-setup': {display: 'hidden'},
    'processing': {display: 'hidden'},
    'frequency-response-reference': {display: 'hidden'},
    'distortion-processing': {display: 'hidden'},
    'polar-data-setup': {display: 'hidden'},
    'measurement-setup': {display: 'hidden'},
    'exciter-setup': {display: 'hidden'},
    'amplifier-setup': {display: 'hidden'},
    'elf-v2': {display: 'hidden'},
    'manual': {display: 'hidden'},
    'lt360ex': {display: 'hidden'},
    'wendefix': {display: 'hidden'},
    'knarrzi': {display: 'hidden'},
    'st-neumann': {display: 'hidden'},
    'et250-3d': {display: 'hidden'},
    'antv1_azi_micarc_ele': {display: 'hidden'},  
}