export default {
  'display-range': 'Display range',
  'axes-scaling': 'Axes scaling',
  'legend-visibility': 'Legend visibility',
  'channel-visibility': 'Channel visibility',
  'set-comment': 'Set comment',
  'set-unwrapped-phase-offset': 'Set unwrapped phase offset',
  'set-measurement-info': 'Set measurement info',
  'jump-to-ir-start': 'Jump to IR start',
  'make-left-cursor-active': 'Make left cursor active',
  'make-right-cursor-active': 'Make right cursor active',
  'set-left-cursor-position': 'Set left cursor position',
  'set-right-cursor-position': 'Set right cursor position',
  'set-cursor-distance': 'Set cursor distance',
  'pull-cursors-together': 'Pull cursors together',
  'jump-to-max-active-channel': 'Jump to max. active channel',
  'jump-to-max-all-channels': 'Jump to max. all channels',
  'jump-to-min-active-channel': 'Jump to min. active channel',
  'jump-to-min-all-channels': 'Jump to min. all channels',
  'active-cursor-to-center': 'Active cursor to center',
  'view-all-xy': 'View all xy',
  'view-all-x': 'View all x',
  'view-all-y': 'View all y',
  'cursor-all': 'Cursor all',
  'display-configuration': 'Display configuration',
  'reset-legend': 'Reset legend',
  'copy-legend': 'Copy legend',
  'paste-legend': 'Paste legend',
  'copy-stat-to-legend': 'Copy stat to legend',
  'filename-to-legend': 'Filename to legend',
  'filename-to-title': 'Filename to title',
}
